name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (specify the version you need)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Install Playwright and its dependencies
      - name: Install Playwright browsers
        run: |
          npx playwright install

      # Step 5: Run the Playwright tests
      - name: Run Playwright tests with list and allure-playwright as reporters
        run: |
          npx playwright test --reporter=list,allure-playwright

      # Step 6: Install allure command line
      - name: Install Allure command line
        run: |
          npm install -g allure-commandline --save-dev          

      # Step 7: Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate ./allure-results -o ./allure-report

      # Step 8: Upload Allure results as an artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/          

      # Step 9: Optionally upload the generated Allure report as an artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/